
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package net.venaglia.nondairy.soylang.lexer.cupparser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SP_LITERAL = 53;
  public static final int GT = 84;
  public static final int DELPACKAGE = 42;
  public static final int TEMPLATE_TEXT = 2;
  public static final int PARAM = 41;
  public static final int NOTEQ = 95;
  public static final int TAB_LITERAL = 57;
  public static final int LBRACE_ERROR = 111;
  public static final int BRACE_IN_STRING = 108;
  public static final int PACKAGE_IDENTIFIER = 23;
  public static final int NAMESPACE = 43;
  public static final int RBRACK = 79;
  public static final int STRING_LITERAL_ESCAPE = 73;
  public static final int COMMA = 104;
  public static final int STRING_LITERAL_END = 71;
  public static final int RBRACE = 81;
  public static final int DIRECTIVE_COMMA = 63;
  public static final int RPAREN = 77;
  public static final int LBRACK = 78;
  public static final int LT = 85;
  public static final int LBRACE = 80;
  public static final int DELCALL = 40;
  public static final int LPAREN = 76;
  public static final int QUESTION_DOT = 90;
  public static final int LITERAL = 32;
  public static final int NOT = 86;
  public static final int INTEGER_LITERAL = 68;
  public static final int ILLEGAL_CLOSE_TAG = 114;
  public static final int TAG_RBRACE = 6;
  public static final int ILLEGAL_TAG_DECLARATION = 113;
  public static final int PARAMETER_REF = 21;
  public static final int UNEXPECTED_EOF_IN_LITERAL_BLOCK = 115;
  public static final int DUPLICATE_NAMESPACE_DECLARATION = 106;
  public static final int DOC_COMMENT_BAD_CHARACTER = 20;
  public static final int EQ = 82;
  public static final int TAG_LBRACE = 5;
  public static final int BAD_STRING_ESCAPE = 107;
  public static final int MOD = 101;
  public static final int BOOLEAN_LITERAL = 67;
  public static final int DOC_COMMENT_TAG = 15;
  public static final int CAPTURED_IDENTIFIER = 27;
  public static final int STRING_PARAMETER_REF = 22;
  public static final int PIPE = 102;
  public static final int ALIAS = 44;
  public static final int PLUS = 96;
  public static final int UNTERMINATED_TEMPLATE = 110;
  public static final int CR_LITERAL = 55;
  public static final int QUESTION = 89;
  public static final int LINE_COMMENT = 11;
  public static final int ELSE_IF = 47;
  public static final int CAPTURED_FUNCTION_IDENTIFIER = 28;
  public static final int SWITCH = 36;
  public static final int FOR = 38;
  public static final int TEMPLATE_IDENTIFIER = 25;
  public static final int DIV = 100;
  public static final int MULT = 99;
  public static final int DOC_COMMENT_WHITESPACE = 14;
  public static final int ELSE = 48;
  public static final int DOC_COMMENT_EOL = 13;
  public static final int TAG_END_RBRACE = 8;
  public static final int UNEXPECTED_EOF_DOC_COMMENT = 118;
  public static final int GTEQ = 94;
  public static final int DOT = 103;
  public static final int STRING_LITERAL_BEGIN = 70;
  public static final int RBRACE_ERROR = 112;
  public static final int NULL_LITERAL = 66;
  public static final int STRING_LITERAL = 72;
  public static final int EQEQ = 83;
  public static final int EOF = 0;
  public static final int LF_LITERAL = 56;
  public static final int TAG_END_LBRACE = 7;
  public static final int COMMENT = 10;
  public static final int DEFAULT = 50;
  public static final int NIL_LITERAL = 54;
  public static final int LITERAL_TEXT = 4;
  public static final int PRINT = 45;
  public static final int UNTERMINATED_STRING_LITERAL = 109;
  public static final int DUPLICATE_DELPACKAGE_DECLARATION = 105;
  public static final int LB_LITERAL = 58;
  public static final int MINUS = 98;
  public static final int LTEQ = 93;
  public static final int EMPTY_ARRAY_LITERAL = 74;
  public static final int LET_IDENTIFIER = 29;
  public static final int IGNORED_TEXT = 3;
  public static final int MSG = 33;
  public static final int NAMESPACE_IDENTIFIER = 24;
  public static final int IN = 64;
  public static final int OR = 88;
  public static final int DIRECTIVE_IDENTIFIER = 60;
  public static final int error = 1;
  public static final int DELTEMPLATE_IDENTIFIER = 26;
  public static final int DELTEMPLATE = 31;
  public static final int DOC_COMMENT_BEGIN = 18;
  public static final int WHITESPACE = 9;
  public static final int IF = 35;
  public static final int DOC_COMMENT_END = 19;
  public static final int IF_EMPTY = 51;
  public static final int COLON = 92;
  public static final int DIRECTIVE_PIPE = 61;
  public static final int DOC_COMMENT_IDENTIFIER = 17;
  public static final int TEMPLATE = 30;
  public static final int UNEXPECTED_EOF_IN_TAG_DECLARATION = 116;
  public static final int DIRECTIVE_COLON = 62;
  public static final int FOREACH = 37;
  public static final int DOC_COMMENT_PARAM_TAG = 16;
  public static final int CASE = 49;
  public static final int RANGE = 65;
  public static final int UNEXPECTED_EOF_IN_STRING_LITERAL = 117;
  public static final int RB_LITERAL = 59;
  public static final int AND = 87;
  public static final int UMINUS = 97;
  public static final int DOC_COMMENT = 12;
  public static final int LET = 34;
  public static final int EMPTY_OBJECT_LITERAL = 75;
  public static final int CALL = 39;
  public static final int PRINT_IMPLICIT = 46;
  public static final int CSS = 52;
  public static final int FLOATING_POINT_LITERAL = 69;
  public static final int ELVIS = 91;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TEMPLATE_TEXT",
  "IGNORED_TEXT",
  "LITERAL_TEXT",
  "TAG_LBRACE",
  "TAG_RBRACE",
  "TAG_END_LBRACE",
  "TAG_END_RBRACE",
  "WHITESPACE",
  "COMMENT",
  "LINE_COMMENT",
  "DOC_COMMENT",
  "DOC_COMMENT_EOL",
  "DOC_COMMENT_WHITESPACE",
  "DOC_COMMENT_TAG",
  "DOC_COMMENT_PARAM_TAG",
  "DOC_COMMENT_IDENTIFIER",
  "DOC_COMMENT_BEGIN",
  "DOC_COMMENT_END",
  "DOC_COMMENT_BAD_CHARACTER",
  "PARAMETER_REF",
  "STRING_PARAMETER_REF",
  "PACKAGE_IDENTIFIER",
  "NAMESPACE_IDENTIFIER",
  "TEMPLATE_IDENTIFIER",
  "DELTEMPLATE_IDENTIFIER",
  "CAPTURED_IDENTIFIER",
  "CAPTURED_FUNCTION_IDENTIFIER",
  "LET_IDENTIFIER",
  "TEMPLATE",
  "DELTEMPLATE",
  "LITERAL",
  "MSG",
  "LET",
  "IF",
  "SWITCH",
  "FOREACH",
  "FOR",
  "CALL",
  "DELCALL",
  "PARAM",
  "DELPACKAGE",
  "NAMESPACE",
  "ALIAS",
  "PRINT",
  "PRINT_IMPLICIT",
  "ELSE_IF",
  "ELSE",
  "CASE",
  "DEFAULT",
  "IF_EMPTY",
  "CSS",
  "SP_LITERAL",
  "NIL_LITERAL",
  "CR_LITERAL",
  "LF_LITERAL",
  "TAB_LITERAL",
  "LB_LITERAL",
  "RB_LITERAL",
  "DIRECTIVE_IDENTIFIER",
  "DIRECTIVE_PIPE",
  "DIRECTIVE_COLON",
  "DIRECTIVE_COMMA",
  "IN",
  "RANGE",
  "NULL_LITERAL",
  "BOOLEAN_LITERAL",
  "INTEGER_LITERAL",
  "FLOATING_POINT_LITERAL",
  "STRING_LITERAL_BEGIN",
  "STRING_LITERAL_END",
  "STRING_LITERAL",
  "STRING_LITERAL_ESCAPE",
  "EMPTY_ARRAY_LITERAL",
  "EMPTY_OBJECT_LITERAL",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "EQ",
  "EQEQ",
  "GT",
  "LT",
  "NOT",
  "AND",
  "OR",
  "QUESTION",
  "QUESTION_DOT",
  "ELVIS",
  "COLON",
  "LTEQ",
  "GTEQ",
  "NOTEQ",
  "PLUS",
  "UMINUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "PIPE",
  "DOT",
  "COMMA",
  "DUPLICATE_DELPACKAGE_DECLARATION",
  "DUPLICATE_NAMESPACE_DECLARATION",
  "BAD_STRING_ESCAPE",
  "BRACE_IN_STRING",
  "UNTERMINATED_STRING_LITERAL",
  "UNTERMINATED_TEMPLATE",
  "LBRACE_ERROR",
  "RBRACE_ERROR",
  "ILLEGAL_TAG_DECLARATION",
  "ILLEGAL_CLOSE_TAG",
  "UNEXPECTED_EOF_IN_LITERAL_BLOCK",
  "UNEXPECTED_EOF_IN_TAG_DECLARATION",
  "UNEXPECTED_EOF_IN_STRING_LITERAL",
  "UNEXPECTED_EOF_DOC_COMMENT"
  };
}

