/* The following code was generated by JFlex 1.4.3 on 8/21/10 5:16 PM */

/*
   Copyright 2010 Ed Venaglia

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

package net.venaglia.nondairy.soylang.lexer;

import static com.intellij.psi.xml.XmlTokenType.*;
import static net.venaglia.nondairy.soylang.lexer.SoyToken.*;

import java.util.regex.Matcher;
import com.intellij.psi.tree.IElementType;

@SuppressWarnings({ "ALL" })


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 8/21/10 5:16 PM from the specification file
 * <tt>src/net/venaglia/nondairy/soylang/lexer/soy.flex</tt>
 */
class SoyScanner extends BaseSoyScanner implements com.intellij.lexer.FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int HTML_COMMENT = 44;
  public static final int STRING_PARAM = 26;
  public static final int HTML_ATTRIBUTE_VALUE_2 = 42;
  public static final int HTML_ATTRIBUTE_VALUE_1 = 40;
  public static final int LITERAL_BLOCK = 8;
  public static final int HTML_TAG_START = 30;
  public static final int SOY_TAG = 6;
  public static final int TEMPLATE_TAG = 12;
  public static final int CLOSE_TAG = 4;
  public static final int STRING = 24;
  public static final int NAMESPACE_TAG = 10;
  public static final int HTML_INITIAL = 28;
  public static final int HTML_ATTRIBUTE_VALUE = 38;
  public static final int DOCS_BOL = 20;
  public static final int HTML_ATTRIBUTE_EQ = 36;
  public static final int DOCS_IDENT = 22;
  public static final int TAG_DIRECTIVE = 16;
  public static final int IDENTIFIER_TAG = 14;
  public static final int DOCS = 18;
  public static final int YYINITIAL = 0;
  public static final int OPEN_TAG = 2;
  public static final int HTML_ATTRIBUTE_NAME = 34;
  public static final int HTML_TAG_END = 32;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7, 
     8,  8,  9,  9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 
    16, 16, 17, 17, 18, 18, 19, 19, 20, 20, 21, 21, 22, 22
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\66\1\22"+
    "\1\35\1\6\1\67\1\37\1\72\1\56\1\57\1\5\1\21\1\71"+
    "\1\32\1\10\1\4\1\13\1\74\1\73\1\100\1\75\1\12\1\101"+
    "\1\76\1\77\1\12\1\65\1\40\1\63\1\62\1\33\1\64\1\7"+
    "\6\15\21\34\1\14\2\34\1\60\1\16\1\61\1\0\1\11\1\0"+
    "\1\30\1\55\1\45\1\52\1\20\1\47\1\46\1\51\1\25\2\34"+
    "\1\24\1\42\1\41\1\53\1\44\1\34\1\27\1\43\1\26\1\17"+
    "\1\34\1\50\1\36\1\54\1\34\1\23\1\70\1\31\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\27\0\1\1\2\2\1\1\1\3\1\4\1\5\1\6"+
    "\6\5\1\7\7\5\2\10\1\11\1\12\2\2\1\13"+
    "\1\14\1\12\1\15\1\16\2\17\1\20\1\21\1\22"+
    "\2\16\1\23\1\24\1\25\3\16\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\12\1\36\1\37"+
    "\1\40\1\21\1\41\1\0\1\42\1\43\1\44\2\42"+
    "\1\45\1\44\2\46\1\44\2\46\1\47\1\50\1\51"+
    "\1\52\2\53\1\52\1\54\3\52\2\55\1\52\1\54"+
    "\1\56\1\57\2\60\1\0\1\61\1\0\1\62\1\63"+
    "\1\2\1\63\1\3\1\64\1\63\1\64\1\65\1\66"+
    "\1\67\1\64\1\70\1\3\1\71\1\72\1\73\1\74"+
    "\1\75\1\76\1\3\1\77\1\64\1\100\1\76\1\3"+
    "\1\101\1\0\2\1\1\102\1\0\2\103\1\3\1\4"+
    "\11\0\1\104\13\0\1\105\1\106\1\0\1\107\1\110"+
    "\1\0\1\111\4\0\2\16\1\112\1\0\1\113\3\16"+
    "\1\114\1\115\1\116\1\117\4\0\1\120\1\45\1\0"+
    "\1\121\1\0\3\46\1\122\1\123\2\124\1\125\1\126"+
    "\1\125\1\127\1\130\1\131\1\132\1\133\1\134\1\135"+
    "\1\136\1\63\1\137\1\0\1\3\1\0\1\140\2\0"+
    "\1\141\1\142\1\3\1\143\1\3\2\0\1\144\1\3"+
    "\3\0\2\102\1\0\1\145\1\146\1\147\1\150\1\151"+
    "\2\0\1\152\1\153\2\0\1\154\3\0\1\155\10\0"+
    "\1\156\1\0\1\157\1\160\2\161\1\0\1\16\1\162"+
    "\1\0\1\16\1\163\1\16\4\0\3\46\1\124\2\0"+
    "\1\164\1\165\1\0\1\65\4\0\1\166\5\0\1\167"+
    "\1\0\1\170\5\0\1\171\1\172\3\0\1\161\1\173"+
    "\1\174\1\0\1\175\1\16\2\0\1\174\1\175\1\46"+
    "\1\124\1\0\1\176\1\0\1\177\3\0\1\200\10\0"+
    "\1\201\1\202\2\0\1\160\1\0\1\161\1\0\1\203"+
    "\2\0\1\203\1\124\11\0\1\204\1\205\2\0\1\161"+
    "\3\0\1\206\1\207\2\0\1\210\4\0\1\211\2\0"+
    "\1\161\3\0\1\206\1\0\1\212\1\213\2\0\1\214"+
    "\1\215\1\161\4\0\1\216\1\0\1\161\4\0\1\217"+
    "\1\161\2\0\1\220\1\0\1\221";

  private static int [] zzUnpackAction() {
    int [] result = new int[423];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\102\0\204\0\306\0\u0108\0\u014a\0\u018c\0\u01ce"+
    "\0\u0210\0\u0252\0\u0294\0\u02d6\0\u0318\0\u035a\0\u039c\0\u03de"+
    "\0\u0420\0\u0462\0\u04a4\0\u04e6\0\u0528\0\u056a\0\u05ac\0\u05ee"+
    "\0\u0630\0\u0672\0\u06b4\0\u06f6\0\u0738\0\u077a\0\u077a\0\u07bc"+
    "\0\u07fe\0\u0840\0\u0882\0\u08c4\0\u0906\0\u0948\0\u098a\0\u09cc"+
    "\0\u0a0e\0\u0a50\0\u0a92\0\u0ad4\0\u0b16\0\u077a\0\u0b58\0\u0b9a"+
    "\0\u077a\0\u0bdc\0\u077a\0\u0c1e\0\u077a\0\u0c60\0\u077a\0\u0ca2"+
    "\0\u0ce4\0\u0d26\0\u077a\0\u0d68\0\u077a\0\u0daa\0\u0dec\0\u0e2e"+
    "\0\u0e70\0\u0eb2\0\u0ef4\0\u0f36\0\u0f78\0\u077a\0\u077a\0\u077a"+
    "\0\u077a\0\u0fba\0\u0ffc\0\u077a\0\u077a\0\u103e\0\u077a\0\u077a"+
    "\0\u077a\0\u1080\0\u10c2\0\u1104\0\u077a\0\u1146\0\u077a\0\u1188"+
    "\0\u11ca\0\u120c\0\u124e\0\u1290\0\u12d2\0\u0e70\0\u1314\0\u1356"+
    "\0\u077a\0\u077a\0\u077a\0\u1398\0\u13da\0\u077a\0\u141c\0\u077a"+
    "\0\u145e\0\u14a0\0\u14e2\0\u1524\0\u077a\0\u1566\0\u14a0\0\u15a8"+
    "\0\u15ea\0\u162c\0\u077a\0\u166e\0\u077a\0\u16b0\0\u077a\0\u16f2"+
    "\0\u1734\0\u1776\0\u17b8\0\u077a\0\u17fa\0\u183c\0\u187e\0\u18c0"+
    "\0\u077a\0\u1902\0\u1944\0\u1986\0\u077a\0\u077a\0\u19c8\0\u077a"+
    "\0\u077a\0\u1a0a\0\u1a4c\0\u077a\0\u1a8e\0\u077a\0\u1ad0\0\u1b12"+
    "\0\u1b54\0\u1b96\0\u1bd8\0\u1c1a\0\u1c5c\0\u1c9e\0\u077a\0\u1ce0"+
    "\0\u1d22\0\u077a\0\u1d64\0\u1da6\0\u1de8\0\u1e2a\0\u1e6c\0\u1eae"+
    "\0\u1ef0\0\u1f32\0\u1f74\0\u077a\0\u1fb6\0\u1ff8\0\u203a\0\u207c"+
    "\0\u20be\0\u2100\0\u2142\0\u2184\0\u21c6\0\u2208\0\u224a\0\u228c"+
    "\0\u077a\0\u22ce\0\u2310\0\u2352\0\u2394\0\u077a\0\u23d6\0\u2418"+
    "\0\u245a\0\u249c\0\u24de\0\u2520\0\u077a\0\u2562\0\u077a\0\u25a4"+
    "\0\u25e6\0\u2628\0\u0ca2\0\u077a\0\u077a\0\u077a\0\u266a\0\u26ac"+
    "\0\u26ee\0\u2730\0\u2772\0\u27b4\0\u27f6\0\u2838\0\u287a\0\u28bc"+
    "\0\u28fe\0\u2940\0\u077a\0\u077a\0\u2982\0\u29c4\0\u077a\0\u077a"+
    "\0\u2a06\0\u077a\0\u077a\0\u077a\0\u077a\0\u077a\0\u077a\0\u077a"+
    "\0\u2a48\0\u2a8a\0\u077a\0\u2acc\0\u2b0e\0\u2b50\0\u077a\0\u2b92"+
    "\0\u2bd4\0\u077a\0\u077a\0\u2c16\0\u077a\0\u2c58\0\u2c9a\0\u2cdc"+
    "\0\u077a\0\u2d1e\0\u2d60\0\u2da2\0\u1bd8\0\u2de4\0\u077a\0\u2e26"+
    "\0\u2e68\0\u077a\0\u077a\0\u077a\0\u077a\0\u2eaa\0\u2eec\0\u077a"+
    "\0\u077a\0\u2f2e\0\u2f70\0\u077a\0\u2fb2\0\u2ff4\0\u3036\0\u077a"+
    "\0\u3078\0\u30ba\0\u30fc\0\u313e\0\u3180\0\u31c2\0\u3204\0\u3246"+
    "\0\u077a\0\u2e68\0\u077a\0\u3288\0\u32ca\0\u245a\0\u330c\0\u334e"+
    "\0\u0ca2\0\u3390\0\u33d2\0\u0ca2\0\u3414\0\u3456\0\u3498\0\u34da"+
    "\0\u1188\0\u351c\0\u355e\0\u35a0\0\u35e2\0\u3624\0\u2a8a\0\u077a"+
    "\0\u077a\0\u3666\0\u36a8\0\u36ea\0\u372c\0\u376e\0\u37b0\0\u077a"+
    "\0\u37f2\0\u3834\0\u3876\0\u38b8\0\u38fa\0\u077a\0\u393c\0\u077a"+
    "\0\u397e\0\u39c0\0\u3a02\0\u3a44\0\u3a86\0\u077a\0\u077a\0\u3ac8"+
    "\0\u3b0a\0\u3b4c\0\u3b8e\0\u077a\0\u0ca2\0\u3bd0\0\u0ca2\0\u3c12"+
    "\0\u3c54\0\u3c96\0\u1290\0\u1290\0\u3cd8\0\u3d1a\0\u3d5c\0\u077a"+
    "\0\u3d9e\0\u077a\0\u3de0\0\u3e22\0\u3e64\0\u077a\0\u3ea6\0\u3ee8"+
    "\0\u3f2a\0\u3f6c\0\u3fae\0\u3ff0\0\u4032\0\u4074\0\u077a\0\u077a"+
    "\0\u40b6\0\u40f8\0\u413a\0\u413a\0\u417c\0\u41be\0\u0ca2\0\u4200"+
    "\0\u4242\0\u1290\0\u4284\0\u42c6\0\u4308\0\u434a\0\u438c\0\u43ce"+
    "\0\u4410\0\u4452\0\u4494\0\u44d6\0\u077a\0\u077a\0\u4518\0\u455a"+
    "\0\u459c\0\u45de\0\u4620\0\u4662\0\u46a4\0\u077a\0\u46e6\0\u4728"+
    "\0\u077a\0\u476a\0\u47ac\0\u47ee\0\u4830\0\u077a\0\u4872\0\u48b4"+
    "\0\u48f6\0\u4938\0\u497a\0\u49bc\0\u077a\0\u49fe\0\u077a\0\u077a"+
    "\0\u4a40\0\u4a82\0\u077a\0\u077a\0\u4ac4\0\u4b06\0\u4b48\0\u4b8a"+
    "\0\u4bcc\0\u077a\0\u4c0e\0\u4c50\0\u4c92\0\u4cd4\0\u4d16\0\u4d58"+
    "\0\u077a\0\u077a\0\u4d9a\0\u4ddc\0\u077a\0\u4e1e\0\u077a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[423];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\30\2\31\1\32\1\33\16\30\1\34\5\30\1\35"+
    "\50\30\2\36\1\0\1\36\1\37\11\36\1\40\1\36"+
    "\1\41\3\36\1\42\1\43\1\44\1\45\1\36\1\46"+
    "\7\36\1\47\1\50\1\51\1\52\1\53\1\36\1\54"+
    "\2\36\1\55\27\36\1\56\3\31\1\57\24\56\1\60"+
    "\50\56\1\61\1\62\2\63\1\64\1\65\1\66\1\61"+
    "\1\67\1\70\1\71\1\72\2\70\1\61\2\70\1\73"+
    "\1\74\1\75\2\70\1\76\1\70\1\77\1\100\1\101"+
    "\1\102\1\70\1\61\1\70\2\61\1\103\5\70\1\104"+
    "\3\70\1\105\2\70\1\106\1\107\1\110\1\111\1\112"+
    "\1\113\1\114\1\115\1\116\1\117\1\120\1\121\1\122"+
    "\7\71\23\123\1\124\56\123\1\125\3\31\5\125\1\126"+
    "\2\125\2\126\1\125\2\126\3\125\5\126\1\127\2\125"+
    "\1\126\1\125\1\126\2\125\15\126\25\125\3\31\4\125"+
    "\1\130\20\125\1\127\51\125\3\31\4\125\1\131\1\132"+
    "\2\125\2\132\1\125\2\132\3\125\5\132\1\127\2\125"+
    "\1\132\1\125\1\132\2\125\15\132\24\125\1\127\3\31"+
    "\2\127\1\133\2\127\1\134\1\71\1\72\2\134\1\127"+
    "\2\134\1\127\1\74\1\127\2\134\1\135\2\134\1\127"+
    "\1\136\1\127\1\134\1\127\1\134\2\127\1\137\5\134"+
    "\1\140\6\134\7\127\1\141\2\127\1\142\1\143\1\122"+
    "\7\71\1\144\1\145\1\146\2\144\1\147\74\144\1\150"+
    "\3\151\1\150\1\152\1\150\1\153\73\150\1\154\1\155"+
    "\1\156\1\150\1\157\3\150\1\160\2\150\2\160\1\150"+
    "\2\160\3\150\5\160\3\150\1\160\1\150\1\160\2\150"+
    "\15\160\24\150\1\161\1\162\1\163\13\161\1\164\3\161"+
    "\1\165\47\161\1\165\7\161\6\0\1\166\13\0\1\167"+
    "\47\0\1\167\7\0\1\170\2\31\1\171\1\172\16\170"+
    "\1\173\5\170\1\35\1\170\1\174\3\170\1\175\23\170"+
    "\1\176\16\170\2\174\1\0\6\174\1\177\2\174\2\177"+
    "\1\174\2\177\3\174\5\177\3\174\1\177\1\174\1\177"+
    "\2\174\15\177\25\174\3\200\27\174\1\201\47\174\3\200"+
    "\1\202\4\174\1\203\2\174\2\203\1\174\2\203\2\174"+
    "\1\204\5\203\1\35\1\174\1\201\1\203\1\174\1\203"+
    "\2\174\15\203\24\174\1\205\3\200\56\205\1\206\20\205"+
    "\3\200\5\205\1\207\2\205\2\207\1\205\2\207\1\205"+
    "\1\210\1\205\5\207\3\205\1\207\1\205\1\207\2\205"+
    "\15\207\14\205\1\211\7\205\23\212\1\213\5\212\1\35"+
    "\1\212\1\214\3\212\1\215\23\212\1\174\6\212\1\216"+
    "\7\212\22\217\1\216\1\220\5\217\1\35\1\217\1\214"+
    "\3\217\1\215\23\217\1\174\16\217\32\221\1\222\47\221"+
    "\1\30\2\0\1\30\1\223\16\30\1\0\5\30\1\0"+
    "\50\30\1\0\3\31\76\0\1\224\2\31\1\32\1\0"+
    "\16\224\1\0\5\224\1\0\50\224\4\0\1\225\1\226"+
    "\74\0\1\227\3\0\1\230\16\227\1\231\5\227\1\0"+
    "\50\227\31\0\1\232\200\0\1\233\1\234\11\0\1\235"+
    "\64\0\1\236\102\0\1\237\27\0\1\240\73\0\1\241"+
    "\52\0\1\242\136\0\1\243\55\0\1\244\75\0\1\245"+
    "\2\0\1\246\114\0\1\247\102\0\1\250\3\0\1\251"+
    "\60\0\1\252\1\253\101\0\1\254\12\0\1\255\111\0"+
    "\1\256\46\0\1\257\112\0\1\260\101\0\1\261\52\0"+
    "\1\63\103\0\1\225\1\262\23\0\1\263\61\0\1\264"+
    "\2\0\2\264\1\0\2\264\3\0\5\264\3\0\1\264"+
    "\1\0\1\264\2\0\15\264\25\0\3\265\5\0\5\70"+
    "\1\0\2\70\3\0\5\70\3\0\1\70\1\0\1\70"+
    "\2\0\15\70\1\266\14\0\7\70\10\0\1\267\1\0"+
    "\2\71\57\0\7\71\10\0\1\267\1\0\2\270\1\271"+
    "\21\0\1\271\34\0\7\270\6\0\1\272\74\0\3\265"+
    "\5\0\5\70\1\0\2\70\3\0\3\70\1\273\1\70"+
    "\3\0\1\70\1\0\1\70\2\0\15\70\1\266\14\0"+
    "\7\70\1\0\3\265\5\0\5\70\1\0\2\70\3\0"+
    "\5\70\3\0\1\70\1\0\1\70\2\0\1\274\14\70"+
    "\1\266\14\0\7\70\31\0\1\275\143\0\1\276\70\0"+
    "\1\277\20\0\3\265\5\0\5\70\1\0\1\300\1\70"+
    "\3\0\5\70\3\0\1\70\1\0\1\70\2\0\12\70"+
    "\1\301\2\70\1\266\14\0\7\70\1\0\3\265\5\0"+
    "\5\70\1\0\2\70\3\0\4\70\1\302\3\0\1\70"+
    "\1\0\1\70\2\0\15\70\1\266\14\0\7\70\1\0"+
    "\3\265\5\0\5\70\1\0\2\70\3\0\3\70\1\303"+
    "\1\70\3\0\1\70\1\0\1\70\2\0\15\70\1\266"+
    "\14\0\7\70\62\0\1\304\101\0\1\305\101\0\1\306"+
    "\25\0\1\307\73\0\23\123\1\310\62\123\1\311\75\123"+
    "\10\0\1\312\5\126\1\0\2\126\3\0\5\126\3\0"+
    "\1\126\1\0\1\126\2\0\15\126\15\0\7\126\11\0"+
    "\1\313\2\0\2\313\1\0\2\313\3\0\5\313\3\0"+
    "\1\313\1\0\1\313\2\0\15\313\35\0\1\314\2\0"+
    "\2\314\1\0\2\314\3\0\5\314\3\0\1\314\1\0"+
    "\1\314\2\0\15\314\34\0\1\315\5\132\1\0\2\132"+
    "\3\0\5\132\3\0\1\132\1\0\1\132\2\0\15\132"+
    "\15\0\7\132\11\0\1\316\2\0\2\316\1\0\2\316"+
    "\3\0\5\316\3\0\1\316\1\0\1\316\2\0\15\316"+
    "\34\0\1\317\5\134\1\0\2\134\3\0\5\134\3\0"+
    "\1\134\1\0\1\134\2\0\15\134\15\0\7\134\10\0"+
    "\1\317\5\134\1\0\2\134\3\0\3\134\1\320\1\134"+
    "\3\0\1\134\1\0\1\134\2\0\15\134\15\0\7\134"+
    "\10\0\1\317\5\134\1\0\1\321\1\134\3\0\5\134"+
    "\3\0\1\134\1\0\1\134\2\0\15\134\15\0\7\134"+
    "\10\0\1\317\5\134\1\0\2\134\3\0\4\134\1\322"+
    "\3\0\1\134\1\0\1\134\2\0\15\134\15\0\7\134"+
    "\1\144\2\0\2\144\1\0\74\144\2\0\1\146\103\0"+
    "\1\323\76\0\3\151\102\0\1\324\106\0\1\325\2\0"+
    "\2\325\1\0\2\325\3\0\5\325\3\0\1\325\1\0"+
    "\1\325\2\0\3\325\1\326\11\325\26\0\1\155\102\0"+
    "\1\156\107\0\5\160\1\0\2\160\3\0\5\160\3\0"+
    "\1\160\1\0\1\160\2\0\15\160\15\0\7\160\1\161"+
    "\2\0\13\161\1\0\3\161\1\0\47\161\1\0\7\161"+
    "\2\0\1\163\77\0\2\327\1\0\13\327\1\330\1\331"+
    "\2\327\1\332\3\327\1\333\1\334\11\327\1\335\5\327"+
    "\1\336\5\327\1\337\14\327\1\340\7\327\11\0\1\341"+
    "\2\0\2\341\1\0\2\341\3\0\5\341\3\0\1\341"+
    "\1\0\1\341\2\0\15\341\24\0\1\170\2\0\1\170"+
    "\1\342\16\170\1\0\5\170\1\0\1\170\1\0\3\170"+
    "\1\175\23\170\1\0\16\170\1\175\2\31\1\171\1\0"+
    "\16\175\1\0\5\175\1\0\1\175\1\0\27\175\1\0"+
    "\16\175\4\0\1\225\1\262\74\0\1\343\3\0\1\344"+
    "\16\343\1\345\5\343\1\0\50\343\1\175\2\0\1\175"+
    "\1\0\16\175\1\0\5\175\1\0\1\175\1\0\27\175"+
    "\1\0\16\175\4\0\1\346\4\0\1\347\2\0\2\347"+
    "\1\0\2\347\3\0\5\347\3\0\1\347\1\0\1\347"+
    "\2\0\15\347\10\0\1\350\24\0\5\177\1\0\2\177"+
    "\3\0\5\177\1\0\1\177\1\0\1\177\1\0\1\177"+
    "\2\0\15\177\7\0\1\351\5\0\7\177\1\0\3\200"+
    "\131\0\1\352\57\0\5\203\1\0\2\203\3\0\5\203"+
    "\1\0\1\203\1\0\1\203\1\0\1\203\2\0\15\203"+
    "\15\0\7\203\1\353\3\0\17\353\1\354\5\353\1\0"+
    "\50\353\11\0\5\207\1\0\2\207\3\0\5\207\1\0"+
    "\1\207\1\0\1\207\1\0\1\207\2\0\15\207\15\0"+
    "\7\207\23\212\1\0\5\212\1\0\1\212\1\0\3\212"+
    "\1\0\23\212\1\0\6\212\1\0\7\212\1\355\3\0"+
    "\17\355\1\356\5\355\1\0\50\355\14\0\2\357\1\0"+
    "\2\357\3\0\5\357\3\0\1\357\1\360\1\357\2\0"+
    "\15\357\24\0\22\217\2\0\5\217\1\0\1\217\1\0"+
    "\3\217\1\0\23\217\1\0\16\217\1\361\3\0\17\361"+
    "\1\362\5\361\1\0\50\361\32\221\1\363\101\221\1\364"+
    "\47\221\1\223\2\0\1\365\17\223\1\0\5\223\1\0"+
    "\50\223\1\224\2\0\1\224\1\0\16\224\1\0\5\224"+
    "\1\0\50\224\1\225\1\366\1\367\77\225\5\370\1\371"+
    "\74\370\1\372\3\0\25\372\1\0\50\372\1\227\3\0"+
    "\1\230\24\227\1\0\50\227\11\373\5\0\1\373\2\0"+
    "\3\373\5\0\3\373\1\0\1\373\1\0\2\373\15\0"+
    "\15\373\7\0\11\374\5\0\1\374\2\0\3\374\5\0"+
    "\3\374\1\0\1\374\1\0\2\374\15\0\15\374\7\0"+
    "\11\375\5\0\1\375\2\0\3\375\5\0\3\375\1\0"+
    "\1\375\1\0\2\375\15\0\15\375\52\0\1\376\64\0"+
    "\1\377\53\0\11\u0100\5\0\1\u0100\2\0\3\u0100\5\0"+
    "\3\u0100\1\0\1\u0100\1\0\2\u0100\15\0\15\u0100\7\0"+
    "\11\u0101\5\0\1\u0101\1\0\1\u0102\3\u0101\5\0\3\u0101"+
    "\1\0\1\u0101\1\0\2\u0101\15\0\15\u0101\51\0\1\u0103"+
    "\37\0\11\u0104\5\0\1\u0104\2\0\3\u0104\5\0\3\u0104"+
    "\1\0\1\u0104\1\0\2\u0104\15\0\15\u0104\33\0\1\u0105"+
    "\117\0\1\u0106\105\0\1\u0107\33\0\11\u0108\5\0\1\u0108"+
    "\2\0\3\u0108\5\0\3\u0108\1\0\1\u0108\1\0\2\u0108"+
    "\15\0\15\u0108\34\0\1\u0109\101\0\1\u010a\103\0\1\u010b"+
    "\76\0\1\u010c\16\0\1\u010d\101\0\1\u010e\65\0\1\u010f"+
    "\121\0\1\u0110\63\0\1\u0111\50\0\5\370\1\u0112\74\370"+
    "\31\0\1\u0113\61\0\5\264\1\0\2\264\3\0\5\264"+
    "\3\0\1\264\1\0\1\264\2\0\15\264\15\0\7\264"+
    "\1\0\3\265\52\0\1\266\35\0\2\u0114\57\0\7\u0114"+
    "\10\0\1\267\1\0\2\270\57\0\7\270\12\0\1\u0115"+
    "\1\u0116\1\0\1\u0115\2\0\1\u0115\7\0\1\u0115\14\0"+
    "\1\u0115\1\0\1\u0115\2\0\1\u0115\2\0\1\u0115\15\0"+
    "\7\u0115\11\0\1\u0117\2\0\2\u0117\1\0\2\u0117\3\0"+
    "\5\u0117\3\0\1\u0117\1\0\1\u0117\2\0\15\u0117\25\0"+
    "\3\265\5\0\5\70\1\0\1\u0118\1\70\3\0\5\70"+
    "\3\0\1\70\1\0\1\70\2\0\15\70\1\266\14\0"+
    "\7\70\1\0\3\265\5\0\5\70\1\0\2\70\3\0"+
    "\5\70\3\0\1\70\1\0\1\70\2\0\11\70\1\u0119"+
    "\3\70\1\266\14\0\7\70\74\0\1\u011a\6\0\3\265"+
    "\5\0\5\70\1\0\2\70\3\0\1\u011b\4\70\3\0"+
    "\1\70\1\0\1\70\2\0\15\70\1\266\14\0\7\70"+
    "\1\0\3\265\5\0\5\70\1\0\2\70\3\0\2\70"+
    "\1\u011c\2\70\3\0\1\70\1\0\1\70\2\0\15\70"+
    "\1\266\14\0\7\70\1\0\3\265\5\0\5\70\1\0"+
    "\2\70\3\0\1\u011d\4\70\3\0\1\70\1\0\1\70"+
    "\2\0\15\70\1\266\14\0\7\70\11\0\1\u011e\2\0"+
    "\2\u011e\1\0\2\u011e\3\0\5\u011e\3\0\1\u011e\1\0"+
    "\1\u011e\2\0\15\u011e\24\0\4\123\1\u011f\121\123\1\u0120"+
    "\55\123\11\0\1\126\2\0\2\126\1\0\2\126\3\0"+
    "\5\126\3\0\1\126\1\0\1\126\2\0\15\126\34\0"+
    "\1\u0121\5\313\1\0\2\313\3\0\5\313\3\0\1\313"+
    "\1\0\1\313\2\0\15\313\15\0\7\313\11\0\5\314"+
    "\1\0\2\314\3\0\5\314\3\0\1\314\1\0\1\314"+
    "\2\0\15\314\15\0\7\314\11\0\1\132\2\0\2\132"+
    "\1\0\2\132\3\0\5\132\3\0\1\132\1\0\1\132"+
    "\2\0\15\132\35\0\5\316\1\0\2\316\3\0\5\316"+
    "\3\0\1\316\1\0\1\316\2\0\15\316\15\0\7\316"+
    "\11\0\1\134\2\0\2\134\1\0\2\134\3\0\5\134"+
    "\3\0\1\134\1\0\1\134\2\0\15\134\34\0\1\317"+
    "\5\134\1\0\1\u0122\1\134\3\0\5\134\3\0\1\134"+
    "\1\0\1\134\2\0\15\134\15\0\7\134\10\0\1\317"+
    "\5\134\1\0\2\134\3\0\1\u0123\4\134\3\0\1\134"+
    "\1\0\1\134\2\0\15\134\15\0\7\134\10\0\1\317"+
    "\5\134\1\0\2\134\3\0\1\u0124\4\134\3\0\1\134"+
    "\1\0\1\134\2\0\15\134\15\0\7\134\11\0\5\325"+
    "\1\0\2\325\3\0\5\325\3\0\1\325\1\0\1\325"+
    "\2\0\15\325\15\0\7\325\11\0\5\325\1\0\2\325"+
    "\3\0\4\325\1\u0125\3\0\1\325\1\0\1\325\2\0"+
    "\15\325\15\0\7\325\12\0\2\u0126\1\0\1\u0126\2\0"+
    "\1\u0126\7\0\1\u0126\14\0\1\u0126\1\0\1\u0126\2\0"+
    "\1\u0126\2\0\1\u0126\15\0\7\u0126\11\0\5\341\1\0"+
    "\2\341\3\0\5\341\3\0\1\341\1\0\1\341\2\0"+
    "\15\341\15\0\7\341\1\342\2\0\1\u0127\17\342\1\0"+
    "\5\342\1\0\1\342\1\0\3\342\1\0\23\342\1\0"+
    "\16\342\1\u0128\4\0\24\u0128\1\0\50\u0128\1\343\3\0"+
    "\1\344\24\343\1\0\50\343\11\0\1\u0129\2\0\2\u0129"+
    "\1\0\2\u0129\3\0\5\u0129\3\0\1\u0129\1\0\1\u0129"+
    "\2\0\15\u0129\56\0\1\u012a\60\0\1\u012b\2\0\2\u012b"+
    "\1\0\2\u012b\3\0\5\u012b\3\0\1\u012b\1\0\1\u012b"+
    "\2\0\15\u012b\24\0\1\353\3\0\25\353\1\0\50\353"+
    "\1\355\3\0\25\355\1\0\50\355\12\0\4\u012c\1\0"+
    "\2\u012c\3\0\5\u012c\3\0\1\u012c\1\0\1\u012c\2\0"+
    "\15\u012c\15\0\7\u012c\12\0\1\u012d\23\0\1\u012e\34\0"+
    "\7\u012d\1\361\3\0\25\361\1\0\50\361\32\221\1\u012f"+
    "\102\221\1\u0130\46\221\2\0\1\367\77\0\5\370\1\u0131"+
    "\74\370\4\0\1\367\1\u0112\114\0\1\u0132\101\0\1\u0133"+
    "\123\0\1\u0134\103\0\1\u0135\35\0\11\u0136\5\0\1\u0136"+
    "\2\0\3\u0136\5\0\3\u0136\1\0\1\u0136\1\0\2\u0136"+
    "\15\0\15\u0136\27\0\1\u0137\61\0\11\u0138\5\0\1\u0138"+
    "\2\0\3\u0138\5\0\3\u0138\1\0\1\u0138\1\0\2\u0138"+
    "\15\0\15\u0138\35\0\1\u0139\114\0\1\u013a\70\0\1\u013b"+
    "\75\0\1\u013c\75\0\1\u013d\61\0\11\u013e\5\0\1\u013e"+
    "\2\0\3\u013e\5\0\3\u013e\1\0\1\u013e\1\0\2\u013e"+
    "\15\0\15\u013e\7\0\11\u013f\5\0\1\u013f\1\0\1\u0140"+
    "\3\u013f\5\0\3\u013f\1\0\1\u013f\1\0\2\u013f\15\0"+
    "\15\u013f\37\0\1\u0141\63\0\2\u0114\4\0\1\u0142\52\0"+
    "\7\u0114\12\0\2\u0143\1\0\1\u0143\2\0\1\u0143\7\0"+
    "\1\u0143\14\0\1\u0143\1\0\1\u0143\2\0\1\u0143\2\0"+
    "\1\u0143\15\0\7\u0143\11\0\5\u0117\1\0\2\u0117\1\0"+
    "\1\u0144\1\0\5\u0117\3\0\1\u0117\1\0\1\u0117\2\0"+
    "\15\u0117\15\0\7\u0117\1\0\3\265\5\0\5\70\1\0"+
    "\1\70\1\u0145\3\0\5\70\3\0\1\70\1\0\1\70"+
    "\2\0\15\70\1\266\14\0\7\70\75\0\1\u0146\5\0"+
    "\3\265\5\0\5\70\1\0\2\70\3\0\1\u0147\4\70"+
    "\3\0\1\70\1\0\1\70\2\0\15\70\1\266\14\0"+
    "\7\70\1\0\3\265\5\0\5\70\1\0\2\70\3\0"+
    "\5\70\3\0\1\70\1\0\1\70\2\0\2\70\1\u0148"+
    "\12\70\1\266\14\0\7\70\11\0\5\u011e\1\0\2\u011e"+
    "\3\0\5\u011e\3\0\1\u011e\1\0\1\u011e\2\0\15\u011e"+
    "\14\0\1\u0144\7\u011e\24\123\1\u0149\102\123\1\u014a\54\123"+
    "\10\0\1\317\5\134\1\0\1\134\1\u014b\3\0\5\134"+
    "\3\0\1\134\1\0\1\134\2\0\15\134\15\0\7\134"+
    "\10\0\1\317\5\134\1\0\2\134\3\0\1\u014c\4\134"+
    "\3\0\1\134\1\0\1\134\2\0\15\134\15\0\7\134"+
    "\10\0\1\317\5\134\1\0\2\134\3\0\5\134\3\0"+
    "\1\134\1\0\1\134\2\0\2\134\1\u014d\12\134\15\0"+
    "\7\134\11\0\5\325\1\0\2\325\3\0\3\325\1\u014e"+
    "\1\325\3\0\1\325\1\0\1\325\2\0\15\325\15\0"+
    "\7\325\12\0\2\u014f\1\0\1\u014f\2\0\1\u014f\7\0"+
    "\1\u014f\14\0\1\u014f\1\0\1\u014f\2\0\1\u014f\2\0"+
    "\1\u014f\15\0\7\u014f\32\0\1\u0150\60\0\5\u012b\1\0"+
    "\2\u012b\3\0\5\u012b\1\0\1\u012b\1\0\1\u012b\1\0"+
    "\1\u012b\2\0\15\u012b\15\0\7\u012b\12\0\4\u0151\1\0"+
    "\2\u0151\3\0\5\u0151\3\0\1\u0151\1\0\1\u0151\1\0"+
    "\1\u0152\15\u0151\15\0\7\u0151\12\0\2\u012d\21\0\1\u0153"+
    "\35\0\7\u012d\12\0\1\u0154\1\u0155\1\0\1\u0154\2\0"+
    "\1\u0154\7\0\1\u0154\14\0\1\u0154\1\0\1\u0154\2\0"+
    "\1\u0154\2\0\1\u0154\15\0\7\u0154\33\221\1\0\46\221"+
    "\4\370\1\367\1\u0131\74\370\11\u0156\5\0\1\u0156\2\0"+
    "\3\u0156\1\0\1\u0157\3\0\3\u0156\1\0\1\u0156\1\0"+
    "\2\u0156\15\0\15\u0156\36\0\1\u0158\116\0\1\u0159\61\0"+
    "\1\u015a\120\0\1\u015b\103\0\1\u015c\62\0\1\u015d\115\0"+
    "\1\u015e\37\0\11\u015f\5\0\1\u015f\2\0\3\u015f\5\0"+
    "\3\u015f\1\0\1\u015f\1\0\2\u015f\15\0\15\u015f\7\0"+
    "\11\u0160\5\0\1\u0160\2\0\3\u0160\5\0\3\u0160\1\0"+
    "\1\u0160\1\0\2\u0160\15\0\15\u0160\37\0\1\u0161\70\0"+
    "\1\u0162\74\0\2\u0163\5\0\1\u0164\10\0\1\u0164\40\0"+
    "\7\u0163\12\0\2\u0165\1\0\1\u0165\2\0\1\u0165\7\0"+
    "\1\u0165\14\0\1\u0165\1\0\1\u0165\2\0\1\u0165\2\0"+
    "\1\u0165\15\0\7\u0165\76\0\1\u0166\4\0\3\265\5\0"+
    "\5\70\1\0\1\70\1\u0167\3\0\5\70\3\0\1\70"+
    "\1\0\1\70\2\0\15\70\1\266\14\0\7\70\25\123"+
    "\1\u0168\102\123\1\u0169\53\123\10\0\1\317\5\134\1\0"+
    "\1\134\1\u016a\3\0\5\134\3\0\1\134\1\0\1\134"+
    "\2\0\15\134\15\0\7\134\11\0\5\325\1\0\2\325"+
    "\3\0\4\325\1\u016b\3\0\1\325\1\0\1\325\2\0"+
    "\15\325\15\0\7\325\12\0\2\u016c\1\0\1\u016c\2\0"+
    "\1\u016c\7\0\1\u016c\14\0\1\u016c\1\0\1\u016c\2\0"+
    "\1\u016c\2\0\1\u016c\15\0\7\u016c\12\0\4\u016d\1\0"+
    "\2\u016d\3\0\5\u016d\3\0\1\u016d\1\0\1\u016d\1\0"+
    "\1\u0152\15\u016d\15\0\7\u016d\13\0\1\u0155\100\0\2\u016e"+
    "\1\0\1\u016e\2\0\1\u016e\7\0\1\u016e\7\0\1\u0152"+
    "\4\0\1\u016e\1\0\1\u016e\2\0\1\u016e\2\0\1\u016e"+
    "\15\0\7\u016e\40\0\1\u0152\110\0\1\u016f\62\0\1\u0170"+
    "\77\0\1\u0171\103\0\1\u0172\115\0\1\u0173\106\0\1\u0174"+
    "\30\0\11\u0175\5\0\1\u0175\2\0\3\u0175\5\0\3\u0175"+
    "\1\0\1\u0175\1\0\2\u0175\15\0\15\u0175\7\0\11\u0176"+
    "\5\0\1\u0176\2\0\3\u0176\5\0\3\u0176\1\0\1\u0176"+
    "\1\0\2\u0176\15\0\15\u0176\54\0\1\u0177\60\0\1\u0178"+
    "\67\0\2\u0163\57\0\7\u0163\12\0\2\u0179\1\0\1\u0179"+
    "\2\0\1\u0179\7\0\1\u0179\14\0\1\u0179\1\0\1\u0179"+
    "\2\0\1\u0179\2\0\1\u0179\15\0\7\u0179\75\0\1\u017a"+
    "\4\0\26\123\1\u017b\73\123\1\u017c\61\123\11\0\5\325"+
    "\1\0\2\325\3\0\5\325\3\0\1\325\1\0\1\325"+
    "\2\0\1\325\1\u017d\13\325\15\0\7\325\12\0\2\u017e"+
    "\1\0\1\u017e\2\0\1\u017e\7\0\1\u017e\14\0\1\u017e"+
    "\1\0\1\u017e\2\0\1\u017e\2\0\1\u017e\15\0\7\u017e"+
    "\12\0\4\u017f\1\0\2\u017f\3\0\5\u017f\3\0\1\u017f"+
    "\1\0\1\u017f\1\0\1\u0152\15\u017f\15\0\7\u017f\12\0"+
    "\2\u0180\1\0\1\u0180\2\0\1\u0180\7\0\1\u0180\7\0"+
    "\1\u0152\4\0\1\u0180\1\0\1\u0180\2\0\1\u0180\2\0"+
    "\1\u0180\15\0\7\u0180\11\u0181\5\0\1\u0181\2\0\3\u0181"+
    "\5\0\3\u0181\1\0\1\u0181\1\0\2\u0181\15\0\15\u0181"+
    "\33\0\1\u0182\131\0\1\u0183\53\0\1\u0184\103\0\1\u0185"+
    "\51\0\11\u0186\5\0\1\u0186\2\0\3\u0186\5\0\3\u0186"+
    "\1\0\1\u0186\1\0\2\u0186\15\0\15\u0186\60\0\1\u0187"+
    "\56\0\1\u0188\65\0\2\u0189\1\0\1\u0189\2\0\1\u0189"+
    "\7\0\1\u0189\14\0\1\u0189\1\0\1\u0189\2\0\1\u0189"+
    "\2\0\1\u0189\15\0\7\u0189\77\0\1\u018a\2\0\20\123"+
    "\1\u018b\110\123\1\u018c\52\123\11\0\5\325\1\0\2\325"+
    "\3\0\5\325\3\0\1\325\1\0\1\325\2\0\15\325"+
    "\6\0\1\u018d\6\0\7\325\12\0\4\u018e\1\0\2\u018e"+
    "\3\0\5\u018e\3\0\1\u018e\1\0\1\u018e\1\0\1\u0152"+
    "\15\u018e\15\0\7\u018e\12\0\2\u0155\1\0\1\u0155\2\0"+
    "\1\u0155\7\0\1\u0155\7\0\1\u0152\4\0\1\u0155\1\0"+
    "\1\u0155\2\0\1\u0155\2\0\1\u0155\15\0\7\u0155\11\u018f"+
    "\5\0\1\u018f\2\0\3\u018f\5\0\3\u018f\1\0\1\u018f"+
    "\1\0\2\u018f\15\0\15\u018f\7\0\11\u0190\5\0\1\u0190"+
    "\2\0\3\u0190\5\0\3\u0190\1\0\1\u0190\1\0\2\u0190"+
    "\15\0\15\u0190\27\0\1\u0191\126\0\1\u0192\34\0\11\u0193"+
    "\5\0\1\u0193\2\0\3\u0193\5\0\3\u0193\1\0\1\u0193"+
    "\1\0\2\u0193\15\0\15\u0193\7\0\11\u0194\5\0\1\u0194"+
    "\2\0\3\u0194\5\0\3\u0194\1\0\1\u0194\1\0\2\u0194"+
    "\15\0\15\u0194\21\0\2\u0195\1\0\1\u0195\2\0\1\u0195"+
    "\7\0\1\u0195\14\0\1\u0195\1\0\1\u0195\2\0\1\u0195"+
    "\2\0\1\u0195\15\0\7\u0195\100\0\1\u0196\1\0\27\123"+
    "\1\u0197\102\123\1\u0198\51\123\12\0\4\u0199\1\0\2\u0199"+
    "\3\0\5\u0199\3\0\1\u0199\1\0\1\u0199\1\0\1\u0152"+
    "\15\u0199\15\0\7\u0199\11\u019a\5\0\1\u019a\2\0\3\u019a"+
    "\5\0\3\u019a\1\0\1\u019a\1\0\2\u019a\15\0\15\u019a"+
    "\27\0\1\u019b\73\0\2\u019c\1\0\1\u019c\2\0\1\u019c"+
    "\7\0\1\u019c\14\0\1\u019c\1\0\1\u019c\2\0\1\u019c"+
    "\2\0\1\u019c\15\0\7\u019c\101\0\1\u019d\30\123\1\u019e"+
    "\75\123\1\u019f\55\123\12\0\4\u01a0\1\0\2\u01a0\3\0"+
    "\5\u01a0\3\0\1\u01a0\1\0\1\u01a0\1\0\1\u0152\15\u01a0"+
    "\15\0\7\u01a0\11\u01a1\5\0\1\u01a1\2\0\3\u01a1\5\0"+
    "\3\u01a1\1\0\1\u01a1\1\0\2\u01a1\15\0\15\u01a1\21\0"+
    "\2\u01a2\1\0\1\u01a2\2\0\1\u01a2\7\0\1\u01a2\14\0"+
    "\1\u01a2\1\0\1\u01a2\2\0\1\u01a2\2\0\1\u01a2\15\0"+
    "\7\u01a2\75\0\1\u01a3\4\0\24\123\1\u01a4\106\123\1\u01a5"+
    "\50\123\12\0\4\u01a6\1\0\2\u01a6\3\0\5\u01a6\3\0"+
    "\1\u01a6\1\0\1\u01a6\1\0\1\u0152\15\u01a6\15\0\7\u01a6"+
    "\77\0\1\u01a7\2\0\31\123\1\0\50\123\12\0\4\u0155"+
    "\1\0\2\u0155\3\0\5\u0155\3\0\1\u0155\1\0\1\u0155"+
    "\1\0\1\u0152\15\u0155\15\0\7\u0155";

  private static int [] zzUnpackTrans() {
    int [] result = new int[20064];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\27\0\6\1\2\11\16\1\1\11\2\1\1\11\1\1"+
    "\1\11\1\1\1\11\1\1\1\11\3\1\1\11\1\1"+
    "\1\11\10\1\4\11\2\1\2\11\1\1\3\11\2\1"+
    "\1\0\1\11\1\1\1\11\11\1\3\11\2\1\1\11"+
    "\1\1\1\11\4\1\1\11\5\1\1\11\1\0\1\11"+
    "\1\0\1\11\4\1\1\11\4\1\1\11\3\1\2\11"+
    "\1\1\2\11\2\1\1\11\1\1\1\11\3\1\1\0"+
    "\3\1\1\0\1\11\2\1\1\11\11\0\1\11\13\0"+
    "\1\1\1\11\1\0\2\1\1\0\1\11\4\0\2\1"+
    "\1\11\1\0\1\11\4\1\3\11\4\0\2\1\1\0"+
    "\1\1\1\0\3\1\2\11\2\1\2\11\1\1\7\11"+
    "\2\1\1\11\1\0\1\1\1\0\1\11\2\0\2\11"+
    "\1\1\1\11\1\1\2\0\1\11\1\1\3\0\1\1"+
    "\1\11\1\0\1\1\4\11\2\0\2\11\2\0\1\11"+
    "\3\0\1\11\10\0\1\11\1\0\1\11\3\1\1\0"+
    "\2\1\1\0\3\1\4\0\4\1\2\0\2\11\1\0"+
    "\1\1\4\0\1\11\5\0\1\11\1\0\1\11\5\0"+
    "\2\11\3\0\1\1\1\11\1\1\1\0\2\1\2\0"+
    "\4\1\1\0\1\11\1\0\1\11\3\0\1\11\10\0"+
    "\2\11\2\0\1\1\1\0\1\1\1\0\1\1\2\0"+
    "\2\1\11\0\2\11\2\0\1\1\3\0\1\1\1\11"+
    "\2\0\1\11\4\0\1\11\2\0\1\1\3\0\1\11"+
    "\1\0\2\11\2\0\2\11\1\1\4\0\1\11\1\0"+
    "\1\1\4\0\2\11\2\0\1\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[423];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  public SoyScanner() {
    this((java.io.Reader)null);
  }


  SoyScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  SoyScanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 158) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  // For Demetra compatibility
  public void reset(CharSequence buffer, int initialState){
    zzBuffer = buffer;
    zzBufferArray = null; 
    zzCurrentPos = zzMarkedPos = zzStartRead = 0;
    zzPushbackPos = 0;
    zzAtEOF = false;
    zzAtBOL = true;
    zzEndRead = buffer.length();
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL.charAt(zzCurrentPosL)) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL.charAt(zzMarkedPosL) == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL.charAt(zzMarkedPosL) == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 79: 
          { return symbol(NOTEQ);
          }
        case 146: break;
        case 34: 
          { yybegin(SOY_TAG); yypushback(1); return symbol(ILLEGAL_TAG_DECLARATION);
          }
        case 147: break;
        case 114: 
          { return symbol(AND);
          }
        case 148: break;
        case 67: 
          { yybegin(OPEN_TAG);
                                   yypushback(1);
                                   closeTag = false;
                                   doubleBraceTag = yylength() == 2;
                                   currentCommand = null;
                                   nextStateAfterCloseTag = YYINITIAL;
                                   tagStartLine = yyline;
                                   return symbol(TAG_LBRACE, yytext().toString());
          }
        case 149: break;
        case 81: 
          { return symbol(PARAMETER_REF, yytext().toString());
          }
        case 150: break;
        case 76: 
          { return symbol(OR);
          }
        case 151: break;
        case 56: 
          { yybegin(HTML_ATTRIBUTE_EQ); return symbol(XML_EQ);
          }
        case 152: break;
        case 96: 
          { yybegin(HTML_TAG_START);
                                   closeHtml = false;
                                   yypushback(1);
                                   return symbol(XML_START_TAG_START);
          }
        case 153: break;
        case 109: 
          { yypushback(1); yybegin(CLOSE_TAG); return symbol(SP_LITERAL);
          }
        case 154: break;
        case 84: 
          { yybegin(DOCS); return symbol(DOC_COMMENT_TAG, yytext().toString());
          }
        case 155: break;
        case 32: 
          { return symbol(COMMA);
          }
        case 156: break;
        case 1: 
          { return symbol(IGNORED_TEXT, yytext().toString());
          }
        case 157: break;
        case 145: 
          { return symbol(INTEGER_LITERAL, new Integer(Integer.MIN_VALUE));
          }
        case 158: break;
        case 55: 
          { yybegin(HTML_INITIAL); return symbol(XML_TAG_END);
          }
        case 159: break;
        case 50: 
          { yybegin(nextStateAfterString); return symbol(STRING_LITERAL_END, yytext().toString());
          }
        case 160: break;
        case 24: 
          { return symbol(LBRACK);
          }
        case 161: break;
        case 14: 
          { String ident = yytext().toString();
                                   if ("in".equals(ident) && ("for".equals(currentCommand) || "foreach".equals(currentCommand))) {
                                     return symbol(IN);
                                   }
                                   return symbol(CAPTURED_IDENTIFIER, yytext().toString());
          }
        case 162: break;
        case 120: 
          { yypushback(1);
                                   yybegin(closeTag ? CLOSE_TAG : SOY_TAG);
                                   currentCommand = closeTag ? null : yytext().toString();
                                   return symbol(MSG);
          }
        case 163: break;
        case 87: 
          { return symbol(STRING_LITERAL_ESCAPE, "\"");
          }
        case 164: break;
        case 61: 
          { yybegin(HTML_ATTRIBUTE_VALUE_1); return symbol(XML_ATTRIBUTE_VALUE_START_DELIMITER);
          }
        case 165: break;
        case 29: 
          { return symbol(COLON);
          }
        case 166: break;
        case 116: 
          { yybegin(OPEN_TAG);
                                   yypushback(1);
                                   closeTag = true;
                                   doubleBraceTag = yylength() == 3;
                                   currentCommand = null;
                                   nextStateAfterCloseTag = HTML_INITIAL;
                                   tagStartLine = yyline;
                                   return symbol(TAG_END_LBRACE, yytext().toString());
          }
        case 167: break;
        case 93: 
          { return symbol(STRING_LITERAL_ESCAPE, "\'");
          }
        case 168: break;
        case 15: 
          { return symbol(INTEGER_LITERAL, new Integer(yytext().toString()));
          }
        case 169: break;
        case 42: 
          { return symbol(DOC_COMMENT, yytext().toString());
          }
        case 170: break;
        case 106: 
          { yypushback(1); yybegin(CLOSE_TAG); return symbol(LB_LITERAL);
          }
        case 171: break;
        case 99: 
          { yybegin(OPEN_TAG);
                                   yypushback(1);
                                   closeTag = false;
                                   doubleBraceTag = yylength() == 2;
                                   currentCommand = null;
                                   nextStateAfterCloseTag = HTML_ATTRIBUTE_VALUE_1;
                                   tagStartLine = yyline;
                                   return symbol(TAG_LBRACE, yytext().toString());
          }
        case 172: break;
        case 41: 
          { return symbol(DIRECTIVE_COMMA);
          }
        case 173: break;
        case 135: 
          { char val = (char)parseLong(2, yylength(), 16);
                                   return symbol(STRING_LITERAL_ESCAPE, String.valueOf(val));
          }
        case 174: break;
        case 13: 
          { return symbol(DOT);
          }
        case 175: break;
        case 102: 
          { yybegin(OPEN_TAG);
                                   yypushback(1);
                                   closeTag = true;
                                   doubleBraceTag = yylength() == 3;
                                   currentCommand = null;
                                   nextStateAfterCloseTag = YYINITIAL;
                                   tagStartLine = yyline;
                                   return symbol(TAG_END_LBRACE, yytext().toString());
          }
        case 176: break;
        case 44: 
          { yybegin(DOCS); yypushback(1);
          }
        case 177: break;
        case 21: 
          { return symbol(GT);
          }
        case 178: break;
        case 10: 
          { return symbol(ILLEGAL_TAG_DECLARATION, yytext().toString());
          }
        case 179: break;
        case 9: 
          { if (!doubleBraceTag) {
                                     yybegin(nextStateAfterCloseTag);
                                     return symbol(TAG_RBRACE);
                                   }
                                   return symbol(RBRACE);
          }
        case 180: break;
        case 36: 
          { yybegin(CLOSE_TAG); yypushback(1);
          }
        case 181: break;
        case 37: 
          { yybegin(SOY_TAG);
                                   return symbol(capturedIdentifierType, yytext().toString());
          }
        case 182: break;
        case 143: 
          { yypushback(1);
                                   yybegin(NAMESPACE_TAG);
                                   currentCommand = closeTag ? null : yytext().toString();
                                   nextStateAfterCloseTag = YYINITIAL;
                                   return symbol(closeTag ? ILLEGAL_TAG_DECLARATION : NAMESPACE);
          }
        case 183: break;
        case 7: 
          { if (doubleBraceTag) return symbol(RBRACE);
                                   yybegin(currentCommand == null ? YYINITIAL : HTML_INITIAL);
                                   return symbol(RBRACE_ERROR);
          }
        case 184: break;
        case 39: 
          { return symbol(DIRECTIVE_COLON);
          }
        case 185: break;
        case 72: 
          { return symbol(PARAMETER_REF, yytext().toString().substring(1));
          }
        case 186: break;
        case 127: 
          { return symbol(XML_CHAR_ENTITY_REF, yytext());
          }
        case 187: break;
        case 60: 
          { yybegin(HTML_ATTRIBUTE_VALUE_2); return symbol(XML_ATTRIBUTE_VALUE_START_DELIMITER);
          }
        case 188: break;
        case 117: 
          { yybegin(HTML_TAG_START);
                                   closeHtml = true;
                                   yypushback(1);
                                   return symbol(XML_END_TAG_START);
          }
        case 189: break;
        case 140: 
          { yypushback(1);
                                   yybegin(closeTag ? CLOSE_TAG : SOY_TAG);
                                   currentCommand = closeTag ? null : yytext().toString();
                                   return symbol(FOREACH);
          }
        case 190: break;
        case 6: 
          { yybegin(SOY_TAG); yypushback(1);
          }
        case 191: break;
        case 27: 
          { return symbol(LT);
          }
        case 192: break;
        case 38: 
          { return symbol(DIRECTIVE_IDENTIFIER, yytext().toString());
          }
        case 193: break;
        case 65: 
          { return symbol(XML_COMMENT_CHARACTERS);
          }
        case 194: break;
        case 23: 
          { return symbol(RPAREN);
          }
        case 195: break;
        case 107: 
          { yypushback(1);
                                   yybegin(closeTag ? CLOSE_TAG : SOY_TAG);
                                   currentCommand = closeTag ? null : yytext().toString();
                                   return symbol(IF);
          }
        case 196: break;
        case 26: 
          { return symbol(EQ);
          }
        case 197: break;
        case 35: 
          { yybegin(CLOSE_TAG);
                                    if (currentNamespace == null) currentNamespace = yytext().toString();
                                    return symbol(NAMESPACE_IDENTIFIER, yytext().toString());
          }
        case 198: break;
        case 138: 
          { yypushback(1);
                                   yybegin(CLOSE_TAG);
                                   if (closeTag) {
                                     nextStateAfterCloseTag = nextStateAfterLiterealTag;
                                   } else {
                                     nextStateAfterLiterealTag = nextStateAfterCloseTag;
                                     nextStateAfterCloseTag = LITERAL_BLOCK;
                                   }
                                   return symbol(LITERAL);
          }
        case 199: break;
        case 94: 
          { return symbol(STRING_PARAMETER_REF, yytext().toString());
          }
        case 200: break;
        case 45: 
          { yybegin(DOCS_BOL); return symbol(DOC_COMMENT, yytext().toString());
          }
        case 201: break;
        case 142: 
          { yypushback(1);
                                   yybegin(closeTag ? CLOSE_TAG : TEMPLATE_TAG);
                                   currentCommand = closeTag ? null : yytext().toString();
                                   boolean ok = closeTag || currentTemplate == null;
                                   if (closeTag) {
                                     activeDocCommentBuffer = null;
                                     currentTemplate = null;
                                     nextStateAfterCloseTag = YYINITIAL;
                                   } else {
                                     if (activeDocCommentBuffer != null) {
                                       activeDocCommentBuffer.setTemplateDeclarationLine(tagStartLine);
                                     }
                                     nextStateAfterCloseTag = HTML_INITIAL;
                                   }
                                   return symbol(ok ? TEMPLATE : UNTERMINATED_TEMPLATE);
          }
        case 202: break;
        case 63: 
          { yybegin(HTML_INITIAL); return symbol(XML_BAD_CHARACTER);
          }
        case 203: break;
        case 115: 
          { return symbol(NOT);
          }
        case 204: break;
        case 48: 
          { yybegin(SOY_TAG); return symbol(UNTERMINATED_STRING_LITERAL);
          }
        case 205: break;
        case 58: 
          { yybegin(HTML_ATTRIBUTE_VALUE); return symbol(XML_EQ);
          }
        case 206: break;
        case 103: 
          { yypushback(1); yybegin(CLOSE_TAG); return symbol(TAB_LITERAL);
          }
        case 207: break;
        case 89: 
          { return symbol(STRING_LITERAL_ESCAPE, "\r");
          }
        case 208: break;
        case 74: 
          { if (doubleBraceTag) {
                                     yybegin(CLOSE_TAG); yypushback(2);
                                   } else {
                                     yypushback(1);
                                     return symbol(TAG_RBRACE);
                                   }
          }
        case 209: break;
        case 139: 
          { yypushback(1);
                                   yybegin(CLOSE_TAG);
                                   return symbol(closeTag ? ILLEGAL_CLOSE_TAG : IF_EMPTY);
          }
        case 210: break;
        case 53: 
          { yybegin(closeHtml ? HTML_TAG_END : HTML_ATTRIBUTE_NAME); return symbol(XML_TAG_NAME, yytext());
          }
        case 211: break;
        case 40: 
          { return symbol(DIRECTIVE_PIPE);
          }
        case 212: break;
        case 4: 
          { return symbol(RBRACE_ERROR);
          }
        case 213: break;
        case 64: 
          { yybegin(HTML_ATTRIBUTE_NAME); return symbol(XML_ATTRIBUTE_VALUE_END_DELIMITER);
          }
        case 214: break;
        case 113: 
          { return symbol(INTEGER_LITERAL, new Integer((int) parseLong(2, yylength(), 16)));
          }
        case 215: break;
        case 68: 
          { yybegin(currentCommand == null ? YYINITIAL : HTML_INITIAL);
                                   if (!doubleBraceTag) yypushback(1);
                                   return symbol(RBRACE_ERROR);
          }
        case 216: break;
        case 85: 
          { return symbol(BAD_STRING_ESCAPE, yytext().toString());
          }
        case 217: break;
        case 134: 
          { yybegin(DOCS_IDENT); return symbol(DOC_COMMENT_TAG, yytext().toString());
          }
        case 218: break;
        case 105: 
          { yypushback(1); yybegin(CLOSE_TAG); return symbol(LF_LITERAL);
          }
        case 219: break;
        case 18: 
          { return symbol(doubleBraceTag ? LBRACE : LBRACE_ERROR);
          }
        case 220: break;
        case 75: 
          { return symbol(GTEQ);
          }
        case 221: break;
        case 98: 
          { yybegin(OPEN_TAG);
                                   yypushback(1);
                                   closeTag = false;
                                   doubleBraceTag = yylength() == 2;
                                   currentCommand = null;
                                   nextStateAfterCloseTag = HTML_ATTRIBUTE_NAME;
                                   tagStartLine = yyline;
                                   return symbol(TAG_LBRACE, yytext().toString());
          }
        case 222: break;
        case 16: 
          { return symbol(PLUS);
          }
        case 223: break;
        case 144: 
          { yypushback(10); yybegin(currentCommand == null ? YYINITIAL : HTML_INITIAL);
          }
        case 224: break;
        case 108: 
          { yypushback(1); yybegin(CLOSE_TAG); return symbol(RB_LITERAL);
          }
        case 225: break;
        case 119: 
          { yypushback(1); yybegin(CLOSE_TAG); return symbol(NIL_LITERAL);
          }
        case 226: break;
        case 137: 
          { yypushback(1);
                                   yybegin(closeTag ? CLOSE_TAG : SOY_TAG);
                                   currentCommand = closeTag ? null : yytext().toString();
                                   return symbol(SWITCH);
          }
        case 227: break;
        case 22: 
          { return symbol(LPAREN);
          }
        case 228: break;
        case 100: 
          { yybegin(OPEN_TAG);
                                   yypushback(1);
                                   closeTag = false;
                                   doubleBraceTag = yylength() == 2;
                                   currentCommand = null;
                                   nextStateAfterCloseTag = HTML_ATTRIBUTE_VALUE_2;
                                   tagStartLine = yyline;
                                   return symbol(TAG_LBRACE, yytext().toString());
          }
        case 229: break;
        case 46: 
          { yybegin(DOCS); return symbol(DOC_COMMENT_IDENTIFIER, yytext().toString());
          }
        case 230: break;
        case 90: 
          { return symbol(STRING_LITERAL_ESCAPE, "\n");
          }
        case 231: break;
        case 80: 
          { yybegin(SOY_TAG);
                                   currentTemplate = yytext().toString();
                                   if (activeDocCommentBuffer != null) activeDocCommentBuffer.setTemplateName(currentTemplate);
                                   return symbol(TEMPLATE_IDENTIFIER, currentTemplate);
          }
        case 232: break;
        case 20: 
          { return symbol(MINUS);
          }
        case 233: break;
        case 8: 
          { yybegin(nextStateAfterCloseTag); return symbol(RBRACE_ERROR);
          }
        case 234: break;
        case 33: 
          { return symbol(LITERAL_TEXT, yytext().toString());
          }
        case 235: break;
        case 19: 
          { if (doubleBraceTag) return symbol(RBRACE);
                                   yybegin(CLOSE_TAG); yypushback(1);
          }
        case 236: break;
        case 95: 
          { yybegin(OPEN_TAG);
                                   yypushback(1);
                                   closeTag = false;
                                   doubleBraceTag = yylength() == 2;
                                   currentCommand = null;
                                   nextStateAfterCloseTag = HTML_INITIAL;
                                   tagStartLine = yyline;
                                   return symbol(TAG_LBRACE, yytext().toString());
          }
        case 237: break;
        case 47: 
          { return symbol(STRING_LITERAL, yytext().toString());
          }
        case 238: break;
        case 122: 
          { yypushback(1);
                                   yybegin(closeTag ? CLOSE_TAG : SOY_TAG);
                                   currentCommand = closeTag ? null : yytext().toString();
                                   return symbol(FOR);
          }
        case 239: break;
        case 54: 
          { return symbol(TAG_WHITE_SPACE);
          }
        case 240: break;
        case 86: 
          { return symbol(STRING_LITERAL_ESCAPE, "\\");
          }
        case 241: break;
        case 136: 
          { yypushback(1);
                                   yybegin(closeTag ? CLOSE_TAG : SOY_TAG);
                                   currentCommand = closeTag ? null : yytext().toString();
                                   return symbol(closeTag ? ILLEGAL_CLOSE_TAG : ELSE_IF);
          }
        case 242: break;
        case 31: 
          { yybegin(TAG_DIRECTIVE); return symbol(DIRECTIVE_PIPE);
          }
        case 243: break;
        case 112: 
          { return symbol(FLOATING_POINT_LITERAL, new Double(yytext().toString()));
          }
        case 244: break;
        case 82: 
          { yybegin(YYINITIAL); return symbol(DOC_COMMENT_END, yytext().toString());
          }
        case 245: break;
        case 133: 
          { yypushback(1);
                                   capturedIdentifierType = PARAMETER_REF;
                                   yybegin(closeTag ? CLOSE_TAG : IDENTIFIER_TAG);
                                   currentCommand = closeTag ? null : yytext().toString();
                                   return symbol(PARAM);
          }
        case 246: break;
        case 118: 
          { yybegin(HTML_INITIAL); return symbol(XML_COMMENT_END);
          }
        case 247: break;
        case 111: 
          { if (!doubleBraceTag) yypushback(1);
                                   yybegin(CLOSE_TAG); yypushback(3);
          }
        case 248: break;
        case 17: 
          { nextStateAfterString = yystate();
                                   yybegin(STRING);
                                   stringTerminator = yytext().charAt(0);
                                   return symbol(STRING_LITERAL_BEGIN, yytext().toString());
          }
        case 249: break;
        case 83: 
          { yybegin(DOCS); yypushback(2);
          }
        case 250: break;
        case 12: 
          { return symbol(MULT);
          }
        case 251: break;
        case 52: 
          { return symbol(XML_BAD_CHARACTER);
          }
        case 252: break;
        case 123: 
          { nextStateAfterString = yystate();
                                   yybegin(STRING_PARAM);
                                   yypushback(yylength() - 1);
                                   return symbol(STRING_LITERAL_BEGIN, yytext().toString());
          }
        case 253: break;
        case 97: 
          { if (closeHtml) { yypushback(1); return symbol(XML_BAD_CHARACTER); }
                                   yybegin(HTML_INITIAL); return symbol(XML_TAG_END);
          }
        case 254: break;
        case 62: 
          { return symbol(XML_ATTRIBUTE_VALUE_TOKEN, yytext());
          }
        case 255: break;
        case 78: 
          { return symbol(LTEQ);
          }
        case 256: break;
        case 128: 
          { yypushback(1);
                                   yybegin(CLOSE_TAG);
                                   return symbol(closeTag ? ILLEGAL_CLOSE_TAG : ELSE);
          }
        case 257: break;
        case 70: 
          { yybegin(nextStateAfterCloseTag);
                                   if (!doubleBraceTag) yypushback(1);
                                   return symbol(TAG_RBRACE);
          }
        case 258: break;
        case 130: 
          { yypushback(1);
                                   yybegin(closeTag ? CLOSE_TAG : SOY_TAG);
                                   currentCommand = closeTag ? null : yytext().toString();
                                   return symbol(closeTag ? ILLEGAL_CLOSE_TAG : CASE);
          }
        case 259: break;
        case 125: 
          { return symbol(NULL_LITERAL);
          }
        case 260: break;
        case 77: 
          { return symbol(EQEQ);
          }
        case 261: break;
        case 101: 
          { yybegin(DOCS); return symbol(DOC_COMMENT);
          }
        case 262: break;
        case 2: 
          { return symbol(WHITESPACE);
          }
        case 263: break;
        case 59: 
          { yybegin(HTML_ATTRIBUTE_NAME); return symbol(XML_ATTRIBUTE_VALUE_TOKEN);
          }
        case 264: break;
        case 141: 
          { yypushback(1);
                                   yybegin(closeTag ? CLOSE_TAG : SOY_TAG);
                                   currentCommand = closeTag ? null : yytext().toString();
                                   return symbol(closeTag ? ILLEGAL_CLOSE_TAG : DEFAULT);
          }
        case 265: break;
        case 91: 
          { return symbol(STRING_LITERAL_ESCAPE, "\f");
          }
        case 266: break;
        case 132: 
          { yypushback(1);
                                   yybegin(closeTag ? CLOSE_TAG : SOY_TAG);
                                   currentCommand = closeTag ? null : yytext().toString();
                                   return symbol(closeTag ? ILLEGAL_CLOSE_TAG : PRINT);
          }
        case 267: break;
        case 71: 
          { if (doubleBraceTag) { yypushback(1); return symbol(DIV); }
                                   yybegin(CLOSE_TAG); yypushback(2);
          }
        case 268: break;
        case 73: 
          { Matcher matcher = MATCH_NON_IDENTIFIER_CHAR.matcher(yytext());
                                   if (matcher.find()) {
                                     yypushback(yylength() - matcher.start());
                                   }
                                   String ident = yytext().toString();
                                   if ("for".equals(currentCommand) && "range".equals(ident)) return symbol(RANGE);
                                   if ("in".equals(ident) && ("for".equals(currentCommand) || "foreach".equals(currentCommand))) {
                                     return symbol(IN);
                                   }
                                   if (EXPRESSION_TOKENS.containsKey(ident)) {
                                     return EXPRESSION_TOKENS.get(ident).toSymbol(this, ident);
                                   }
                                   return symbol(CAPTURED_FUNCTION_IDENTIFIER, ident);
          }
        case 269: break;
        case 30: 
          { return symbol(MOD);
          }
        case 270: break;
        case 5: 
          { yybegin(SOY_TAG);
                                   currentCommand = "";
                                   yypushback(1);
                                   return symbol(PRINT_IMPLICIT);
          }
        case 271: break;
        case 69: 
          { if (!doubleBraceTag) {
                                     yybegin(nextStateAfterCloseTag);
                                     return symbol(TAG_END_RBRACE);
                                   }
                                   yypushback(1);
                                   return symbol(DIV);
          }
        case 272: break;
        case 124: 
          { return symbol(BOOLEAN_LITERAL, new Boolean(true));
          }
        case 273: break;
        case 121: 
          { yypushback(1);
                                   yybegin(closeTag ? CLOSE_TAG : SOY_TAG);
                                   currentCommand = closeTag ? null : yytext().toString();
                                   return symbol(closeTag ? ILLEGAL_CLOSE_TAG : CSS);
          }
        case 274: break;
        case 57: 
          { yypushback(1); yybegin(HTML_ATTRIBUTE_NAME);
          }
        case 275: break;
        case 88: 
          { return symbol(STRING_LITERAL_ESCAPE, "\t");
          }
        case 276: break;
        case 43: 
          { yybegin(DOCS_BOL); return symbol(DOC_COMMENT);
          }
        case 277: break;
        case 104: 
          { yypushback(1); yybegin(CLOSE_TAG); return symbol(CR_LITERAL);
          }
        case 278: break;
        case 25: 
          { return symbol(RBRACK);
          }
        case 279: break;
        case 66: 
          { return symbol(COMMENT, yytext().toString());
          }
        case 280: break;
        case 129: 
          { yypushback(1);
                                   capturedIdentifierType = TEMPLATE_IDENTIFIER;
                                   yybegin(closeTag ? CLOSE_TAG : IDENTIFIER_TAG);
                                   currentCommand = closeTag ? null : yytext().toString();
                                   return symbol(CALL);
          }
        case 281: break;
        case 110: 
          { yybegin(nextStateAfterCloseTag);
                                   if (!doubleBraceTag) yypushback(1);
                                   return symbol(TAG_END_RBRACE);
          }
        case 282: break;
        case 126: 
          { yybegin(HTML_COMMENT);
                                   return symbol(XML_COMMENT_START);
          }
        case 283: break;
        case 11: 
          { return symbol(DIV);
          }
        case 284: break;
        case 49: 
          { if (stringTerminator == yytext().charAt(0)) {
                                       yybegin(nextStateAfterString);
                                       return symbol(STRING_LITERAL_END, yytext().toString());
                                   } else {
                                       return symbol(STRING_LITERAL, yytext().toString());
                                   }
          }
        case 285: break;
        case 3: 
          { return symbol(LBRACE_ERROR);
          }
        case 286: break;
        case 51: 
          { return symbol(XML_DATA_CHARACTERS, yytext());
          }
        case 287: break;
        case 92: 
          { return symbol(STRING_LITERAL_ESCAPE, "\b");
          }
        case 288: break;
        case 28: 
          { return symbol(QUESTION);
          }
        case 289: break;
        case 131: 
          { return symbol(BOOLEAN_LITERAL, new Boolean(false));
          }
        case 290: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case HTML_COMMENT: {
              yybegin(YYINITIAL);
            }
            case 424: break;
            case HTML_ATTRIBUTE_VALUE_2: {
              yybegin(YYINITIAL);
            }
            case 425: break;
            case HTML_ATTRIBUTE_VALUE_1: {
              yybegin(YYINITIAL);
            }
            case 426: break;
            case LITERAL_BLOCK: {
              yybegin(YYINITIAL);
            }
            case 427: break;
            case HTML_TAG_START: {
              yybegin(YYINITIAL);
            }
            case 428: break;
            case SOY_TAG: {
              yybegin(YYINITIAL);
            }
            case 429: break;
            case TEMPLATE_TAG: {
              yybegin(YYINITIAL);
            }
            case 430: break;
            case CLOSE_TAG: {
              yybegin(YYINITIAL);
            }
            case 431: break;
            case STRING: {
              yybegin(YYINITIAL);
            }
            case 432: break;
            case NAMESPACE_TAG: {
              yybegin(YYINITIAL);
            }
            case 433: break;
            case HTML_INITIAL: {
              yybegin(YYINITIAL);
            }
            case 434: break;
            case HTML_ATTRIBUTE_VALUE: {
              yybegin(YYINITIAL);
            }
            case 435: break;
            case DOCS_BOL: {
              yybegin(YYINITIAL);
            }
            case 436: break;
            case HTML_ATTRIBUTE_EQ: {
              yybegin(YYINITIAL);
            }
            case 437: break;
            case DOCS_IDENT: {
              yybegin(YYINITIAL);
            }
            case 438: break;
            case TAG_DIRECTIVE: {
              yybegin(YYINITIAL);
            }
            case 439: break;
            case IDENTIFIER_TAG: {
              yybegin(YYINITIAL);
            }
            case 440: break;
            case DOCS: {
              yybegin(YYINITIAL);
            }
            case 441: break;
            case YYINITIAL: {
              return null;
            }
            case 442: break;
            case OPEN_TAG: {
              yybegin(YYINITIAL);
            }
            case 443: break;
            case HTML_ATTRIBUTE_NAME: {
              yybegin(YYINITIAL);
            }
            case 444: break;
            case HTML_TAG_END: {
              yybegin(YYINITIAL);
            }
            case 445: break;
            default:
            return null;
            }
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
